### PR TITLE
Fix parsing of ECS task ID from task ARN

### LINKED ISSUE #29: AWS link output to console is missing task id
## Overview

👋  from the Civic Apps Team.

A few of us (Justin and Jenny, specifically) have ran into the issue below. Thus far, on OAR, Fieldscope and newly Vanguard-Charitable. 

After running an ecs manage command, the link being printed to the console is missing the task ID but instead states the cluster name `ecsStagingCluster`. Seeing the behavior with both 1.1.0 and 2.0.0 versions of ecsmanage ([OAR](https://github.com/open-apparel-registry/open-apparel-registry/issues/1148) and FieldScope/VC respectively). At the time of last testing, this was not happening on Tank Magic who has similar CA-template code as these other projects.

### Problem behavior
```
vagrant@vagrant:/vagrant$ ./scripts/manage ecsmanage showmigrations
Task started! View here:
https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/ecsStagingCluster/details
```

### Correct look
`https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/ee432459-78ff-4efe-86b7-dbd847b54be9/details`

### PR DESCRIPTION
**Pull request by hectcastro**
## Overview

AWS has undergone a change in the way they format ECS task ARNs. Previously, task IDs looked like:

```
 arn:aws:ecs:region:aws_account_id:task/task-id
```

Now, task IDs can also look like:

```
 arn:aws:ecs:region:aws_account_id:task/cluster-name/task-id
```

To account for both versions, always pull the last element of the ARN split by `/`.

Closes #29 

## Notes

For more detail on the ECS task ID formats, see: https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-account-settings.html#ecs-resource-ids

## Testing Instructions

- From within a project exhibiting the symptoms described in #29, install the version of `django-ecsmanage` represented by the branch associated with this PR

```diff
diff --git a/src/django/Dockerfile b/src/django/Dockerfile
index ffa07e5..5c94fee 100644
--- a/src/django/Dockerfile
+++ b/src/django/Dockerfile
@@ -9,6 +9,7 @@ RUN set -ex \
     build-essential \
     " \
     && deps=" \
+    git \
     postgresql-client-12 \
     " \
     && apt-get update && apt-get install -y $buildDeps $deps --no-install-recommends \
diff --git a/src/django/requirements.txt b/src/django/requirements.txt
index dae1c40..62fb992 100644
--- a/src/django/requirements.txt
+++ b/src/django/requirements.txt
@@ -4,7 +4,7 @@ coreapi==2.3.3
 dedupe==1.9.4
 defusedxml==0.6.0
 django-amazon-ses==2.1.1
-django-ecsmanage==2.0.0
+git+https://github.com/azavea/django-ecsmanage.git@feature/hmc/fix-cloudwatch-url#egg=django-ecsmanage
 django-extensions==2.1.9
 django-jsonview==1.2.0
 django-rest-auth[with_social]==0.9.5
```

- After rebuilding the `django` container image, execute `django-ecsmanage` and inspect the URL emitted

```console
$ ./scripts/manage ecsmanage showmigrations
```

- **Optional**: If you want to go even further, toggle the old and new ECS **Task** ARN formats for your IAM user via the [ECS account settings](https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/settings); test using each to ensure both work

```console
$ ./scripts/manage ecsmanage showmigrations
Starting database_1 ... done
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
arn:aws:ecs:eu-west-1:****:task/fcf6c042-1a6c-427d-9a8d-685b1ce9e3de
Task started! View here:
https://console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsStagingCluster/tasks/fcf6c042-1a6c-427d-9a8d-685b1ce9e3de/details
$ ./scripts/manage ecsmanage showmigrations
Starting database_1 ... done
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
arn:aws:ecs:eu-west-1:****:task/ecsStagingCluster/7bde6fe343994224bd592c171e6c6a5f
Task started! View here:
https://console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsStagingCluster/tasks/7bde6fe343994224bd592c171e6c6a5f/details
```

### CODE REVIEW

**Comment by hectcastro** [comment]
Jenny and Justin, please let me know if you can run through these testing instructions with your respective projects. 🙏

**Review by jwalgran — APPROVED** [review]
I verified this fix on the OAR project and [successfully ported it to the FieldScope project](https://github.com/azavea/fieldscope/pull/713) which has a local copy of the command for compatibility with old Python/Django. Thanks for the fix.

**Comment by hectcastro** [comment]
@rbreslow -- please take a pass at reviewing from within the context of VC.

**Review by rbreslow — APPROVED** [review]
Looks good 👍 

```python
>>> "arn:aws:ecs:region:aws_account_id:task/task-id".split("/")[-1]
'task-id'
>>> "arn:aws:ecs:region:aws_account_id:task/cluster-name/task-id".split("/")[-1]
'task-id'
```

**Review by rbreslow — APPROVED** [review]
I verified these changes work with VC as well ✅. 

```console
$ ./scripts/manage ecsmanage showmigrations
Creating vanguard-charitable-charity-search_django_run ... done
Task started! View here:
https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/381b62c282c34c4cbc3f2f20d7282df4/details
```

**Pull request merged**
